name: Sync Obsidian Vault → Notion

on:
  push:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. コードを取得
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Node.js 環境
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. ライブラリをインストール
      - run: npm install @notionhq/client @vrerv/md-to-notion

      # 4. 親ページの存在チェック＆作成（１回だけ）
      - id: ensure_page
        run: |
          ROOT_NAME="Obsidian-sync"
          # 4-a. 既存ページを検索
          EXISTING=$(node << 'EOF'
          import { Client } from "@notionhq/client";
          const notion = new Client({ auth: process.env.NOTION_TOKEN });
          (async () => {
            const res = await notion.search({
              query: ROOT_NAME,
              filter: { property: "object", value: "page" }
            });
            // 最初にヒットしたページIDを返却（なければ空文字）
            console.log(res.results[0]?.id || "");
          })();
          EOF
          )
          # 4-b. なければ作成
          if [ -z "$EXISTING" ]; then
            PAGE_ID=$(node << 'EOF'
            import { Client } from "@notionhq/client";
            const notion = new Client({ auth: process.env.NOTION_TOKEN });
            (async () => {
              const page = await notion.pages.create({
                parent: { page_id: process.env.PARENT_PAGE_ID },
                properties: {
                  title: { title: [{ text: { content: ROOT_NAME } }] }
                }
              });
              console.log(page.id);
            })();
            EOF
            )
          else
            PAGE_ID=$EXISTING
          fi
          echo "PAGE_ID=$PAGE_ID" >> $GITHUB_ENV
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PARENT_PAGE_ID: ${{ secrets.PARENT_PAGE_ID }}

      # 5. Vault ルート全体を Notion に同期
      - name: Sync all Markdown
        run: |
          npx @vrerv/md-to-notion \
            --token "$NOTION_TOKEN" \
            --page-id "$PAGE_ID" \
            --delete \
            --verbose \
            .
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PAGE_ID: ${{ env.PAGE_ID }}
